[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "bun run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
